<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;
use App\User;

class Comment extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'user_id' => $this->user_id,
            'author' => $this->user->name,
            'text' => $this->text,
            'created_at' => $this->created_at->format('h:i A'),
            'visible' => $this->visible,
        ];
    }

    public function with($request)
    {
        return parent::with($request); // TODO: Change the autogenerated stub
    }
}
