<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;
use App\Http\Resources\Reply as ReplyResource;

class Comment extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'user_id' => $this->user_id,
            'author' => $this->user->name,
//            @todo
//            'replies' => ReplyResource::collection($this->replies),
            'replies' => [],
            'replies_count' => count($this->replies),
            'replies_show' => 0,
            'text' => $this->text,
            'created_at' => $this->created_at->format('h:i A'),
        ];
    }

    public function with($request)
    {
        return parent::with($request); // TODO: Change the autogenerated stub
    }
}
